[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
random_word = "0.3"
serde = { version = "1.0", features = ["derive"] }